In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
df=pd.read_csv("data/hotel_bookings.csv")
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [52]:
df.shape

(119390, 32)

In [53]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [54]:
df.head(5)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [55]:
df.rename({'adults':'num_adults','children':'num_children','babies':'num_babies'},inplace=True,axis=1)
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'num_adults', 'num_children', 'num_babies',
       'meal', 'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

## 1. Nan

### Checking NaN

In [56]:
# NaN
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   num_adults                      119390 non-null  int64
 10  num_children                    119386 non-null  float64
 11  num_babies                      119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [57]:

# num_children -> 119386 --> fill the NaN with the mode
# country      ->118902-119390=488(Nan) --> 
# agent        ->103050-119390=16340(Nan) --> 
# company      -> 6797-119390=112593(Nan) --> 

# Instead of the above calculation please folllow below

df.isnull().sum()*100/len(df)

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_year                  0.000000
arrival_date_month                 0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
num_adults                         0.000000
num_children                       0.003350
num_babies                         0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                             13.686238
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

### 1. Droppoing company coz 94% NaN that will not help in any of the situations

In [58]:
df.drop(columns=['company'],inplace=True)
df.head(2)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01

### 2. May we can fill the agent column let see the values whar are there then will do fill

In [59]:
df['agent'].unique()

array([ nan, 304., 240., 303.,  15., 241.,   8., 250., 115.,   5., 175.,
       134., 156., 243., 242.,   3., 105.,  40., 147., 306., 184.,  96.,
         2., 127.,  95., 146.,   9., 177.,   6., 143., 244., 149., 167.,
       300., 171., 305.,  67., 196., 152., 142., 261., 104.,  36.,  26.,
        29., 258., 110.,  71., 181.,  88., 251., 275.,  69., 248., 208.,
       256., 314., 126., 281., 273., 253., 185., 330., 334., 328., 326.,
       321., 324., 313.,  38., 155.,  68., 335., 308., 332.,  94., 348.,
       310., 339., 375.,  66., 327., 387., 298.,  91., 245., 385., 257.,
       393., 168., 405., 249., 315.,  75., 128., 307.,  11., 436.,   1.,
       201., 183., 223., 368., 336., 291., 464., 411., 481.,  10., 154.,
       468., 410., 390., 440., 495., 492., 493., 434.,  57., 531., 420.,
       483., 526., 472., 429.,  16., 446.,  34.,  78., 139., 252., 270.,
        47., 114., 301., 193., 182., 135., 350., 195., 352., 355., 159.,
       363., 384., 360., 331., 367.,  64., 406., 163., 414., 333., 427.,
       431., 430., 426., 438., 433., 418., 441., 282., 432.,  72., 450.,
       180., 454., 455.,  59., 451., 254., 358., 469., 165., 467., 510.,
       337., 476., 502., 527., 479., 508., 535., 302., 497., 187.,  13.,
         7.,  27.,  14.,  22.,  17.,  28.,  42.,  20.,  19.,  45.,  37.,
        61.,  39.,  21.,  24.,  41.,  50.,  30.,  54.,  52.,  12.,  44.,
        31.,  83.,  32.,  63.,  60.,  55.,  56.,  89.,  87., 118.,  86.,
        85., 210., 214., 129., 179., 138., 174., 170., 153.,  93., 151.,
       119.,  35., 173.,  58.,  53., 133.,  79., 235., 192., 191., 236.,
       162., 215., 157., 287., 132., 234.,  98.,  77., 103., 107., 262.,
       220., 121., 205., 378.,  23., 296., 290., 229.,  33., 286., 276.,
       425., 484., 323., 403., 219., 394., 509., 111., 423.,   4.,  70.,
        82.,  81.,  74.,  92.,  99.,  90., 112., 117., 106., 148., 158.,
       144., 211., 213., 216., 232., 150., 267., 227., 247., 278., 280.,
       285., 289., 269., 295., 265., 288., 122., 294., 325., 341., 344.,
       346., 359., 283., 364., 370., 371.,  25., 141., 391., 397., 416.,
       404., 299., 197.,  73., 354., 444., 408., 461., 388., 453., 459.,
       474., 475., 480., 449.])

1. Not finding any similarities in the agent column so we will be filling with the -1 but in reality we have to take knowledge from the client such that what values are suitable for this NaN we have to fill with that value.

2. We can not drop it because there are so many rows will be deleted.

In [60]:
df[df['agent']==5]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
25,Resort Hotel,0,78,2015,July,27,1,2,5,2,...,0,No Deposit,5.0,0,Transient,63.60,1,0,Check-Out,2015-07-08
79,Resort Hotel,0,81,2015,July,27,3,2,6,3,...,0,No Deposit,5.0,0,Transient,85.86,0,0,Check-Out,2015-07-11
155,Resort Hotel,0,82,2015,July,28,5,4,6,2,...,0,No Deposit,5.0,0,Transient,63.60,1,2,Check-Out,2015-07-15
272,Resort Hotel,0,87,2015,July,28,10,2,5,2,...,0,No Deposit,5.0,0,Transient,133.83,0,2,Check-Out,2015-07-17
300,Resort Hotel,0,36,2015,July,28,11,2,5,2,...,0,No Deposit,5.0,0,Transient,104.68,1,0,Check-Out,2015-07-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75021,City Hotel,1,268,2015,July,29,12,2,1,2,...,0,No Deposit,5.0,0,Transient,82.00,0,0,Canceled,2015-06-26
75022,City Hotel,1,268,2015,July,29,12,2,1,2,...,0,No Deposit,5.0,0,Transient,82.00,0,0,Canceled,2015-06-26
75023,City Hotel,1,268,2015,July,29,12,2,1,2,...,0,No Deposit,5.0,0,Transient,82.00,0,0,Canceled,2015-06-26
75024,City Hotel,1,268,2015,July,29,12,2,1,2,...,0,No Deposit,5.0,0,Transient,82.00,0,0,Canceled,2015-06-26
75025,City Hotel,1,268,2015,July,29,12,2,1,2,...,0,No Deposit,5.0,0,Transient,82.00,0,0,Canceled,2015-06-26

In [61]:
df['agent'].fillna(-1,inplace=True)
df['agent'].isnull().sum()

/var/folders/1p/j0f7xvr91cgdwsyvj_1fs0q80000gn/T/ipykernel_1354/3891395547.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['agent'].fillna(-1,inplace=True)

np.int64(0)

### 3. num_children

In [62]:
df['num_children'].isnull().sum() # There are 4 values are NaN Probabli drop

np.int64(4)

In [63]:
df['num_children'].unique() # Checking If we can do somethig

array([ 0.,  1.,  2., 10.,  3., nan])

In [70]:
df[df['num_children'].isnull()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
40600,City Hotel,1,2,2015,August,32,3,1,0,2,...,0,No Deposit,-1.0,0,Transient-Party,12.0,0,1,Canceled,2015-08-01
40667,City Hotel,1,1,2015,August,32,5,0,2,2,...,0,No Deposit,14.0,0,Transient-Party,12.0,0,1,Canceled,2015-08-04
40679,City Hotel,1,1,2015,August,32,5,0,2,3,...,0,No Deposit,-1.0,0,Transient-Party,18.0,0,2,Canceled,2015-08-04
41160,City Hotel,1,8,2015,August,33,13,2,5,2,...,0,No Deposit,9.0,0,Transient-Party,76.5,0,1,Canceled,2015-08-09

In [72]:
# We have to drop rows that contains num_children == Nan
df['num_children'].isnull().sum()
df.dropna(subset=['num_children'],inplace=True)
df['num_children'].isnull().sum()

np.int64(0)

### 4. country

In [66]:
df['country'].isnull().sum()

np.int64(488)

In [67]:
df[df['country'].isnull()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
30,Resort Hotel,0,118,2015,July,27,1,4,10,1,...,2,No Deposit,-1.0,0,Transient,62.0,0,2,Check-Out,2015-07-15
4127,Resort Hotel,1,0,2016,February,8,15,0,0,0,...,0,No Deposit,-1.0,0,Transient,0.0,0,0,Canceled,2016-02-15
7092,Resort Hotel,1,8,2016,July,30,21,0,1,1,...,0,No Deposit,-1.0,0,Transient,73.0,0,2,Canceled,2016-07-20
7860,Resort Hotel,1,39,2016,August,36,30,0,5,2,...,0,No Deposit,-1.0,0,Transient,159.0,0,5,Canceled,2016-07-22
8779,Resort Hotel,1,0,2016,October,42,13,0,1,1,...,0,No Deposit,-1.0,0,Transient,50.0,0,0,Canceled,2016-10-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65908,City Hotel,1,0,2017,April,15,10,0,0,0,...,0,No Deposit,-1.0,0,Transient,0.0,0,0,Canceled,2017-04-10
65909,City Hotel,1,0,2017,April,15,10,0,0,0,...,0,No Deposit,-1.0,0,Transient,0.0,0,0,Canceled,2017-04-10
65910,City Hotel,1,0,2017,April,15,10,0,0,0,...,0,No Deposit,-1.0,0,Transient,0.0,0,0,Canceled,2017-04-10
80830,City Hotel,0,4,2015,November,48,23,1,2,1,...,0,No Deposit,37.0,0,Transient-Party,70.0,0,0,Check-Out,2015-11-26
101488,City Hotel,0,1,2016,November,47,13,2,2,2,...,0,No Deposit,14.0,0,Group,105.0,0,1,Check-Out,2016-11-17

In [74]:
# will be filling with unknown since we cant drop coz 488 rows, we can not add random country
df['country'].fillna('unknow',inplace=True)
df['country'].isnull().sum()

np.int64(0)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 119386 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119386 non-null  object
 1   is_canceled                     119386 non-null  int64
 2   lead_time                       119386 non-null  int64
 3   arrival_date_year               119386 non-null  int64
 4   arrival_date_month              119386 non-null  object
 5   arrival_date_week_number        119386 non-null  int64
 6   arrival_date_day_of_month       119386 non-null  int64
 7   stays_in_weekend_nights         119386 non-null  int64
 8   stays_in_week_nights            119386 non-null  int64
 9   num_adults                      119386 non-null  int64
 10  num_children                    119386 non-null  float64
 11  num_babies                      119386 non-null  int64
 12  meal                            119386 non-null  object
 13  country                         119386 non-null  object
 14  market_segment                  119386 non-null  object
 15  distribution_channel            119386 non-null  object
 16  is_repeated_guest               119386 non-null  int64
 17  previous_cancellations          119386 non-null  int64
 18  previous_bookings_not_canceled  119386 non-null  int64
 19  reserved_room_type              119386 non-null  object
 20  assigned_room_type              119386 non-null  object
 21  booking_changes                 119386 non-null  int64
 22  deposit_type                    119386 non-null  object
 23  agent                           119386 non-null  float64
 24  days_in_waiting_list            119386 non-null  int64
 25  customer_type                   119386 non-null  object
 26  adr                             119386 non-null  float64
 27  required_car_parking_spaces     119386 non-null  int64
 28  total_of_special_requests       119386 non-null  int64
 29  reservation_status              119386 non-null  object
 30  reservation_status_date         119386 non-null  object
dtypes: float64(3), int64(16), object(12)
memory usage: 29.1+ MB

## 2. Data types

### Checking Data types

In [76]:
df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
num_adults                          int64
num_children                      float64
num_babies                          int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [92]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', 200)
# pd.set_option('display.width', None)
# pd.set_option('display.max_colwidth', None)
df.head(2)
df['is_repeated_guest'].unique()

array([0, 1])

In [95]:
print(df['is_canceled'].unique())
df=df.astype({'is_canceled':'boolean','is_repeated_guest':'boolean','num_children':'int'})
df.dtypes

[0 1]

hotel                              object
is_canceled                       boolean
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
num_adults                          int64
num_children                        int64
num_babies                          int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                 boolean
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

### 3. Bins Columns

In [99]:
df['lead_time'].unique()

array([342, 737,   7,  13,  14,   0,   9,  85,  75,  23,  35,  68,  18,
        37,  12,  72, 127,  78,  48,  60,  77,  99, 118,  95,  96,  69,
        45,  40,  15,  36,  43,  70,  16, 107,  47, 113,  90,  50,  93,
        76,   3,   1,  10,   5,  17,  51,  71,  63,  62, 101,   2,  81,
       368, 364, 324,  79,  21, 109, 102,   4,  98,  92,  26,  73, 115,
        86,  52,  29,  30,  33,  32,   8, 100,  44,  80,  97,  64,  39,
        34,  27,  82,  94, 110, 111,  84,  66, 104,  28, 258, 112,  65,
        67,  55,  88,  54, 292,  83, 105, 280, 394,  24, 103, 366, 249,
        22,  91,  11, 108, 106,  31,  87,  41, 304, 117,  59,  53,  58,
       116,  42, 321,  38,  56,  49, 317,   6,  57,  19,  25, 315, 123,
        46,  89,  61, 312, 299, 130,  74, 298, 119,  20, 286, 136, 129,
       124, 327, 131, 460, 140, 114, 139, 122, 137, 126, 120, 128, 135,
       150, 143, 151, 132, 125, 157, 147, 138, 156, 164, 346, 159, 160,
       161, 333, 381, 149, 154, 297, 163, 314, 155, 323, 340, 356, 142,
       328, 144, 336, 248, 302, 175, 344, 382, 146, 170, 166, 338, 167,
       310, 148, 165, 172, 171, 145, 121, 178, 305, 173, 152, 354, 347,
       158, 185, 349, 183, 352, 177, 200, 192, 361, 207, 174, 330, 134,
       350, 334, 283, 153, 197, 133, 241, 193, 235, 194, 261, 260, 216,
       169, 209, 238, 215, 141, 189, 187, 223, 284, 214, 202, 211, 168,
       230, 203, 188, 232, 709, 219, 162, 196, 190, 259, 228, 176, 250,
       201, 186, 199, 180, 206, 205, 224, 222, 182, 210, 275, 212, 229,
       218, 208, 191, 181, 179, 246, 255, 226, 288, 253, 252, 262, 236,
       256, 234, 254, 468, 213, 237, 198, 195, 239, 263, 265, 274, 217,
       220, 307, 221, 233, 257, 227, 276, 225, 264, 311, 277, 204, 290,
       266, 270, 294, 319, 282, 251, 322, 291, 269, 240, 271, 184, 231,
       268, 247, 273, 300, 301, 267, 244, 306, 293, 309, 272, 242, 295,
       285, 243, 308, 398, 303, 245, 424, 279, 331, 281, 339, 434, 357,
       325, 329, 278, 332, 343, 345, 360, 348, 367, 353, 373, 374, 406,
       400, 326, 379, 399, 316, 341, 320, 385, 355, 363, 358, 296, 422,
       390, 335, 370, 376, 375, 397, 289, 542, 403, 383, 384, 359, 393,
       337, 362, 365, 435, 386, 378, 313, 351, 287, 471, 462, 411, 450,
       318, 372, 371, 454, 532, 445, 389, 388, 407, 443, 437, 451, 391,
       405, 412, 419, 420, 426, 433, 440, 429, 418, 447, 461, 605, 457,
       475, 464, 482, 626, 489, 496, 503, 510, 517, 524, 531, 538, 545,
       552, 559, 566, 573, 580, 587, 594, 601, 608, 615, 622, 629, 396,
       410, 395, 423, 408, 409, 448, 465, 387, 414, 476, 479, 467, 490,
       493, 478, 504, 507, 458, 518, 521, 377, 444, 380, 463])

In [ ]:
df['lead_time'].describe() # In order to make bins by using cut() we havr to knoe min and max

count    119386.000000
mean        104.014801
std         106.863286
min           0.000000
25%          18.000000
50%          69.000000
75%         160.000000
max         737.000000
Name: lead_time, dtype: float64

In [102]:
bins=[0,100,200,300,400,500,600,700,800]
labels=['0-100','101-200','201-300','301-400','401-500','501-600','601-700','701-800']
df['lead_time_binned']=pd.cut(df['lead_time'],bins=bins,labels=labels)
df[['lead_time','lead_time_binned']]

        lead_time lead_time_binned
0             342          301-400
1             737          701-800
2               7            0-100
3              13            0-100
4              14            0-100
...           ...              ...
119385         23            0-100
119386        102          101-200
119387         34            0-100
119388        109          101-200
119389        205          201-300

[119386 rows x 2 columns]

### Separate Columns

In [103]:
df.head(3)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,num_children,num_babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,lead_time_binned
0,Resort Hotel,False,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,False,0,0,C,C,3,No Deposit,-1.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,301-400
1,Resort Hotel,False,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,False,0,0,C,C,4,No Deposit,-1.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,701-800
2,Resort Hotel,False,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,Direct,False,0,0,A,C,0,No Deposit,-1.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,0-100